production:
  adapter: mysql2
  encoding: utf8
  database: owums_db
  pool: 5
  username: owums_db
  password: fheman
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  database: owums_db
  pool: 5
  username: owums_db
  password: fheman
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: sqlite3
  database: db/test.db
  pool: 5
